IF NOT EXISTS (SELECT * FROM sys.databases d WHERE d.name = 'TrabalhoLP1N1B1')
	CREATE DATABASE TrabalhoLP1N1B1 

GO
USE TrabalhoLP1N1B1
GO

IF NOT EXISTS (SELECT * FROM sys.tables t WHERE t.name = 'tbCurriculo')
BEGIN
	CREATE TABLE [tbCurriculo]
	(
		-- Campos Básicos
		[Id]						INT				NOT NULL	PRIMARY KEY		IDENTITY(1, 1),
		[CPF]						VARCHAR(14)		NOT NULL,	
		[NOME]						VARCHAR(50)		NOT NULL,
		[ENDERECO]					VARCHAR(100)	NULL,
		[TELEFONE]					VARCHAR(30)		NULL,
		[EMAIL]						VARCHAR(200)	NULL,
		[PRETENSAO_SALARIAL]		FLOAT			NOT NULL,
		[CARGO_PRETENDIDO]			VARCHAR(100)	NOT NULL,

		-- Formação
		[TIPO_FORMACAO_1]			INT				NOT NULL,
		[TITULO_FORMACAO_1]			VARCHAR(50)		NOT NULL,
		[DESCRICAO_FORMACAO_1]		VARCHAR(200)	NOT NULL,
		[DATA_INICIO_FORMACAO_1]	DATE			NOT NULL,
		[DATA_TERMINO_FORMACAO_1]	DATE			NOT NULL,

		[TIPO_FORMACAO_2]			INT				NOT NULL DEFAULT 0,
		[TITULO_FORMACAO_2]			VARCHAR(50)		NULL,
		[DESCRICAO_FORMACAO_2]		VARCHAR(200)	NULL,
		[DATA_INICIO_FORMACAO_2]	DATE			NULL,
		[DATA_TERMINO_FORMACAO_2]	DATE			NULL,

		[TIPO_FORMACAO_3]			INT				NOT NULL DEFAULT 0,
		[TITULO_FORMACAO_3]			VARCHAR(50)		NULL,
		[DESCRICAO_FORMACAO_3]		VARCHAR(200)	NULL,
		[DATA_INICIO_FORMACAO_3]	DATE			NULL,
		[DATA_TERMINO_FORMACAO_3]	DATE			NULL,

		[TIPO_FORMACAO_4]			INT				NOT NULL DEFAULT 0,
		[TITULO_FORMACAO_4]			VARCHAR(50)		NULL,
		[DESCRICAO_FORMACAO_4]		VARCHAR(200)	NULL,
		[DATA_INICIO_FORMACAO_4]	DATE			NULL,
		[DATA_TERMINO_FORMACAO_4]	DATE			NULL,

		[TIPO_FORMACAO_5]			INT				NOT NULL DEFAULT 0,
		[TITULO_FORMACAO_5]			VARCHAR(50)		NULL,
		[DESCRICAO_FORMACAO_5]		VARCHAR(200)	NULL,
		[DATA_INICIO_FORMACAO_5]	DATE			NULL,
		[DATA_TERMINO_FORMACAO_5]	DATE			NULL,

		-- Experiências Profissionais
		[CARGO_OCUPADO_EXP_1]		VARCHAR(100)	NULL,
		[DATA_INICIO_EXP_1]			DATE			NULL,
		[DATA_TERMINO_EXP_1]		DATE			NULL,

		[CARGO_OCUPADO_EXP_2]		VARCHAR(100)	NULL,
		[DATA_INICIO_EXP_2]			DATE			NULL,
		[DATA_TERMINO_EXP_2]		DATE			NULL,
	
		[CARGO_OCUPADO_EXP_3]		VARCHAR(100)	NULL,
		[DATA_INICIO_EXP_3]			DATE			NULL,
		[DATA_TERMINO_EXP_3]		DATE			NULL,

		-- Idiomas
		[IDIOMA_1]					INT				NOT NULL DEFAULT 0,
		[NIVEL_LEITURA_IDIOMA_1]	INT				NOT NULL DEFAULT 0,
		[NIVEL_ESCUTAR_IDIOMA_1]	INT				NOT NULL DEFAULT 0,
		[NIVEL_FALAR_IDIOMA_1]		INT				NOT NULL DEFAULT 0,

		[IDIOMA_2]					INT				NOT NULL DEFAULT 0,
		[NIVEL_LEITURA_IDIOMA_2]	INT				NOT NULL DEFAULT 0,
		[NIVEL_ESCUTAR_IDIOMA_2]	INT				NOT NULL DEFAULT 0,
		[NIVEL_FALAR_IDIOMA_2]		INT				NOT NULL DEFAULT 0,
	
		[IDIOMA_3]					INT				NOT NULL DEFAULT 0,
		[NIVEL_LEITURA_IDIOMA_3]	INT				NOT NULL DEFAULT 0,
		[NIVEL_ESCUTAR_IDIOMA_3]	INT				NOT NULL DEFAULT 0,
		[NIVEL_FALAR_IDIOMA_3]		INT				NOT NULL DEFAULT 0,

		[IDIOMA_4]					INT				NOT NULL DEFAULT 0,
		[NIVEL_LEITURA_IDIOMA_4]	INT				NOT NULL DEFAULT 0,
		[NIVEL_ESCUTAR_IDIOMA_4]	INT				NOT NULL DEFAULT 0,
		[NIVEL_FALAR_IDIOMA_4]		INT				NOT NULL DEFAULT 0,
	
		[IDIOMA_5]					INT				NOT NULL DEFAULT 0,
		[NIVEL_LEITURA_IDIOMA_5]	INT				NOT NULL DEFAULT 0,
		[NIVEL_ESCUTAR_IDIOMA_5]	INT				NOT NULL DEFAULT 0,
		[NIVEL_FALAR_IDIOMA_5]		INT				NOT NULL DEFAULT 0,
	)
END
ELSE
	PRINT 'Tabela de Curriculo Já Criada'